### ISSUE TITLE
API is no-longer returning my device

### ISSUE THREAD

**Issue by iolalimited** [apption-labs/meater-cloud-public-rest-api#35]
Device is on and an active cook is in progress.  The API is returning 200 for /devices but the message is empty.

https://public-api.cloud.meater.com/v1/devices
Response:  @{status=OK; statusCode=200; data=; meta=}
```
Response:  {
    "status":  "OK",
    "statusCode":  200,
    "data":  {
                 "devices":  [

                             ]
             },
    "meta":  {

             }
}
```

Additionally the https://cooks.cloud.meater.com link is also failing to find the cook.

Using this Powershell to test:
-------------------------------------------------------------------------------------------

```
$body = @{
'email' = '<registered email>'
'password' = '<pwd>'
}
$response = Invoke-RestMethod -UseBasicParsing https://public-api.cloud.meater.com/v1/login -ContentType "application/json" -Method POST -Body ( $body | convertto-json)
Write-Host "Token:" $response.data.token

$token = $response.data.token
$response = Invoke-RestMethod -UseBasicParsing https://public-api.cloud.meater.com/v1/devices -ContentType application/json -Headers @{Authorization="Bearer $token"}
Write-Host "Response: " $response
Write-Host "Status: " $response.status
Write-Host "Data: " $response.data[0]
Write-Host "Devices: " $response.data.devices
Write-Host "Devices Count: " $response.data.devices.Count
Write-Host "Device0: " $response.data.devices[0]
Write-Host "DeviceID: " $response.data.devices[0].id

$deviceID = $response.data.devices[0].id
$response = Invoke-RestMethod -UseBasicParsing https://public-api.cloud.meater.com/v1/devices/$deviceID -ContentType application/json -Headers @{Authorization="Bearer $token"}

Write-Host "Cook: " $response.data.cook.name
Write-Host "--------------------"
Write-Host "Cook: " $response.data.cook
Write-Host "Internal: " $response.data.temperature.internal " Target: " $response.data.cook.temperature.target "Ambient: " $response.data.temperature.ambient

#state: One of Not Started, Configured, Started, Ready For Resting, Resting, Slightly Underdone, Finished, Slightly Overdone, OVERCOOK!. Not translated.
Write-Host "State: " $response.data.cook.state
Write-Host "Remaining: " $response.data.cook.time.remaining
```

**Comment by rafalkrol-xyz** [comment]
Hi, @iolalimited!

Thanks for reaching out to us. One of our consumers experienced a slowdown that caused a buildup of messages to be processed. The public API not returning your devices was a symptom of that lag. However, we have addressed the issue, and the public API once again returns the expected results.

Please confirm that everything is back to normal for you so that I can close this issue.

**Comment by iolalimited** [comment]
Thank you.  This is working again now.

Andy

**Comment by Nezmo68** [comment]
Is it possible this problem has reoccured?  I also cannot get any device info returned and still can't as of now.

```
{
	"status": "OK",
	"statusCode": 200,
	"data": {
		"devices": []
	},
	"meta": {}
}
```
I am a new Meater user and trying to use the API for the first time.  So far I have not been able to retrieve my device.  I have completed a cook and confirm that when I run the API GET the Meater is active and connected to the cloud.
